config:
  send_anonymous_usage_stats: False

portfolio:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_DB') }}"
      port: 5432
      user: dbtdev
      pass: "{{ env_var('DBT_PASSWORD') }}"
      dbname: dbt
      schema: dev
    prod:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_DB') }}"
      port: 5432
      user: dbtprod
      pass: "{{ env_var('DBT_PASSWORD') }}"
      dbname: dbt
      schema: prod
  target: dev