services:
  db:
    container_name: postgres
    restart: "no"
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbt
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=dbt
      - POSTGRES_INITDB_ARGS="--auth=md5 --auth-host=md5 --auth-local=md5"
    ports:
      - "5433:5432"
volumes:
  postgres-db-volume:
