version: "2"
services:
  db:
    container_name: postgres
    restart: "no"
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DBT_PASSWORD}
      - POSTGRES_DB=dbt
      - POSTGRES_INITDB_ARGS="--auth=md5"
    ports:
      - "5433:5432"
  etl:
    image: portfolio:latest
    container_name: etl
    ports:
      - 8080:8080
  airflow-db:
    container_name: airflow-database
    restart: "no"
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=${AIRFLOW_DB_PASSWORD}
      - POSTGRES_DB=airflow
      - POSTGRES_INITDB_ARGS="--auth=md5"
    ports:
      - "5434:5432"

volumes:
  postgres-db-volume:
