version: 2

models:
  - name: details
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - actif
            - day
      - dbt_utils.expression_is_true:
          expression: "valo > -50000"
      - dbt_utils.expression_is_true:
          expression: "valo < 100000"
    columns:
      - name: actif
        tests:
          - not_null
      - name: valo
        tests:
          - not_null
  - name: rente
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - action
            - day
      - dbt_utils.expression_is_true:
          expression: "dividende > 0"
      - dbt_utils.expression_is_true:
          expression: "dividende < 100"
    columns:
      - name: action
        tests:
          - not_null
      - name: dividende
        tests:
          - not_null