apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-db-deployment
  labels:
    app: airflow-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-db
  template:
    metadata:
      labels:
        app: airflow-db
    spec:
      containers:
      - name: airflow-db
        image: postgres:latest
        env:
          - name: POSTGRES_DB
            value: "airflow"
          - name: POSTGRES_INITDB_ARGS
            value: "--auth=md5"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: airflow-db-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: airflow-db-secret
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
---

apiVersion: v1
kind: Service
metadata:
  name: airflow-db-service
spec:
  selector:
    app: airflow-db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5432