apiVersion: v1
kind: Secrets
metadata:
  name: portfolio-etl-secret
type: Opaque
data:
  - LOADER_CONNECTION_URI_PROD=postgresql+psycopg2://dbtprod:password1234@portfolio-db-service:5432/dbt
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:password5678@airflow-db-service:5432/airflow