development:
  spreadsheet_id: 1Kcef-JsRvgSVkjGLx0ZxjCEMvGEeVsyoV5_8SBcepbY
  sheet_names:
    - details
    - rente
prod:
  spreadsheet_id: 1Kcef-JsRvgSVkjGLx0ZxjCEMvGEeVsyoV5_8SBcepbY
  sheet_names:
    - details
    - rente
