apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EUXdNekE1TVRRME1Gb1hEVE15TURRd016QTVNVFEwTUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkhxCnROQ0c4dUxVbk1POERqZlNURWJjRFF5eXpNcEVadzBCSncydC92NDl3VlFKM1N0emJyODNNZEgxUEdwQ0xLbmQKQlBPTzZkTlF4U1Y3T1JmR21DbHpDaVdmaUpDQW1FaHVmaHkvaUJkdzk2RHlaYzlJaVVBT1B3YnA4WHQ3a0hmbgp6S0VIbVJmMWNoanljZS8yMUFkNTA2T1hmYVN2ZWJlYjN6bXpqb1czUmhBMlZoUG42WkpTZUVXeTZ2ZmtiMmNRCmZGV3loYm00VjMwdmtBdXhXVlJUd0J4eTdHSGJmcnIwUWFaMTArcWdVWU9aK1poczZGQjdCTEgyenlVRFg5TlcKVDdZUXp4bThUVi9WSVhUUzNLd0FsbDlVMUNmR1phQzZqUGVWVldtd055OHZlU1ozUE1Nc2JhQVJRUkV5dXdIZAoyUldnZm5JTGV6OTFBYmxvMGVFQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZFbzc4S1lmVmNvMGJtSno3S0hFSjBaS0lZdUtNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBYldpUE9XTXM3aEdiNnVoRU9zd2x5MTk3eW9zVmwyTFRPTUQxQ3J0dUNQMmIxZWJocgpiY0o4N3NiOTR2Y2ZWZWNWTFFLMFFPUjFwcFI4amRIckpSbmZ3RzlPM25FSEQzZkZENG5Hakt2Q3liTzNqelJsCjdFcVpvSVFoK2UzazI4aHRTRGVvMXprK0RVVGs5Ylo5YktFRXJkejdINUQ4YXVTbC9FbkY1eTQ1OU4wNDdpaEEKekpaQVFaVkJuRG9ER2FtR3VCUmlpWkI4V2krRmx1RnB4SmVOSTVyckFJZldqclcyR3NjQ2tLZ0RNa3k5MFlwWAp0TzlWMjB3UDd1Mnd0b2NrK1VhNHZLQUNxVkkvMWVmYkp0K3gxWkFCTXZ4Z05RRFBxZ1JReWxEKytvaFliZEx2ClZSdnpabEc1UUJoM2ExQ1J4KzFkL3JwK2ZzWmpvTUtZMEcybgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://a459822d-fbc1-4c73-a915-0f5d7e5b4660.api.k8s.fr-par.scw.cloud:6443
  name: portfolio
contexts:
- context:
    cluster: portfolio
    user: portfolio-admin
  name: admin@portfolio
current-context: admin@portfolio
kind: Config
preferences: {}
users:
- name: portfolio-admin
  user:
    token: opMfB1XZQvdIcoO460vcVJ9Qi3Sfuhsr3NT6csxqOLUgF7N9qvurm5jU
